version: "3.3"
services:
  postgres:
    image: postgres:17
    container_name: borsibaar-db
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - borsibaar-network
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db

  backend:
    image: team31-borsibaar-backend:latest
    container_name: borsibaar-backend
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - borsibaar-network
    secrets:
      - postgres_db

volumes:
  postgres_data:

networks:
  borsibaar-network:
    driver: bridge

secrets:
  postgres_user: 
    external: true
  postgres_password:
    external: true 
  postgres_db:
    external: true