name: Build

on:
  push:
    branches: [ feature/16#16-devops-pipeline-cicd-docker ]
  pull_request:
    branches: [ feature/16#16-devops-pipeline-cicd-docker ]

jobs:
  build-backend:
    name: Backend Build
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t ghcr.io/${{ github.repository_owner }}/team31-borsibaar-backend:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/team31-borsibaar-backend:latest

  build-frontend:
    name: Frontend Build
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        working-directory: ./frontend
        run: docker build -t ghcr.io/${{ github.repository_owner }}/team31-borsibaar-frontend:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/team31-borsibaar-frontend:latest

  deploy-services:
    name: Deploy Services
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    needs: [build-backend, build-frontend]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy with Docker Compose
        run: docker stack deploy -c docker-compose.prod.yaml borsibaar --with-registry-auth